// Копируем ваши константы из allConstants.js
export const titleStates = {
  acuteRhinitis: "Острый ринит",
  acuteTonsillitis: "Острый тонзиллит",
  acutePharyngitis: "Острый фарингит",
  acuteTracheitis: "Острый трахеит",
  acuteBronchitis: "Острый бронхит",
  acuteObstructiveBronchitis: "Острый обструктивный бронхит",
  acuteBronchiolitis: "Острый бронхиолит",
  pleuritis: "Плеврит",
  bronchoectaticLungCondition: "Бронхоэктатическая болезнь",
  chronicRhinitis: "Хронический ринит",
  chronicTonsillitis: "Хронический тонзиллит",
  chronicPharyngitis: "Хронический фарингит",
  cough: "Кашель",
  chronicBronchitis: "Хронический бронхит",
  copd: "ХОБЛ (Хроническая обструктивная болезнь легких)",
  bronchialAsthma: "Бронхиальная астма",
  pneumonia: "Пневмония",
  pneumoniaWithBloodThroating: "Пневмония с кровохарканьем",
  pulmonaryTuberculosis: "Туберкулез легких",
  tela: "ТЭЛА (Тромбоэмболия легочной артерии)",
  pulmonaryInfarction: "Инфаркт легкого",
  pollinosis: "Поллиноз",
  respiratoryProtection: "Защита органов дыхания при помощи респиратора.",
  rejectionBadHabits: "Отказ от вредных привычек.",
  noPathology: "Патологии не выявлено",
};

export const elementsForSurveys = {
  baseSurvey: {
    elementPath: '[data-result="resultSurvey"]',
    date: '[data-result="dateAndTime"]',
    name: '[data-result="name"]',
    age: '[data-result="age"]',
    temperature: '[data-result="temperature"]',
    overview: '[data-result="overview"]',
    listDiagnosis: '[data-result="listDiagnosis"]',
    diagnostics: '[data-result="diagnostics"]',
    treatment: '[data-result="treatment"]',
    otherGuidelines: '[data-result="volumeOfLiquid"]',
  },
  surveyFromAccount: {
    elementPath: '[data-account="resultSurvey"]',
    date: '[data-account="dateAndTime"]',
    name: '[data-account="name"]',
    age: '[data-account="age"]',
    temperature: '[data-account="temperature"]',
    overview: '[data-account="overview"]',
    listDiagnosis: '[data-account="listDiagnosis"]',
    diagnostics: '[data-account="diagnostics"]',
    treatment: '[data-account="treatment"]',
    otherGuidelines: '[data-account="volumeOfLiquid"]',
  },
};