export const titleStates = {
  acuteRhinitis: "acuteRhinitis",
  acuteTonsillitis: "acuteTonsillitis",
  acutePharyngitis: "acutePharyngitis",
  acuteTracheitis: "acuteTracheitis",
  acuteBronchitis: "acuteBronchitis",
  acuteObstructiveBronchitis: "acuteObstructiveBronchitis",
  acuteBronchiolitis: "acuteBronchiolitis",
  pleuritis: "pleuritis",
  bronchoectaticLungCondition: "bronchoectaticLungCondition",
  chronicRhinitis: "chronicRhinitis",
  chronicTonsillitis: "chronicTonsillitis",
  chronicPharyngitis: "chronicPharyngitis",
  cough: "cough",
  chronicBronchitis: "chronicBronchitis",
  copd: "copd",
  bronchialAsthma: "bronchialAsthma",
  pneumonia: "pneumonia",
  pneumoniaWithBloodThroating: "pneumoniaWithBloodThroating",
  pulmonaryTuberculosis: "pulmonaryTuberculosis",
  tela: "tela",
  pulmonaryInfarction: "pulmonaryInfarction",
  pollinosis: "pollinosis",
  respiratoryProtection: "Защита органов дыхания при помощи респиратора.",
  rejectionBadHabits: "Отказ от вредных привычек.",
  noPathology: "noPathology",
};
